const onderwerpen = [
  "De Eiffeltoren",
  "De Taj Mahal",
  "De Grand Canyon",
  "De Sahara",
  "De Amazonerivier",
  "De piramides van Egypte",
  "De Mount Everest",
  "De Victoria Falls",
  "Great Barrier Reef",
  "De Mona Lisa",
  "Elvis Presley",
  "Harry Potter",
  "Leonardo da Vinci",
  "De Beatles",
  "Mickey Mouse",
  "De Big Ben",
  "Disneyland",
  "De Efteling",
  "De Chinese Muur",
  "Voetbal",
  "Liefde",
  "De Titanic",
  "New York City",
  "De Olympische Spelen",
  "De maan",
  "De iPhone",
  "De Rode Zee",
  "De Noordpool",
  "De Atlantische Oceaan",
  "Romeinse Keizerrijk",
  "Griekse mythologie",
  "Boeddhisme",
  "Renaissancekunst",
  "Maya-beschaving",
  "Roaring Twenties",
  "Spaanse Flamenco",
  "Vikingen",
  "Nelson Mandela",
  "Chinese keuken",
  "Fietsen",
  "Tulpen",
  "Kaas",
  "Klompen",
  "Stroopwafels",
  "Anne Frank",
  "Vincent van Gogh",
  "Rembrandt",
  "Grachten",
  "Oranje",
  "Koningsdag",
  "Frietjes",
  "Sinterklaas",
  "Anne Frank Huis",
  "Van Gogh Museum",
  "Rijksmuseum",
  "Eerste Wereldoorlog",
  "Tweede Wereldoorlog",
  "Koeien",
  "Drop",
  "Stroop",
  "Tulpenvelden",
  "Hollandse kaasmarkt",
  "De Nachtwacht",
  "Een leeuw",
  "De Elfstedentocht",
  "Hollandse klederdracht",
  "Dijken",
  "Stamppot",
  "Windenergie",
  "De Nederlandse taal",
  "Windmolens",
  "Architectuur",
  "Regen",
  "Deltawerken",
  "Hollandse Haring",
  "Strandtenten",
  "Polders",
  "Kustlijn",
  "Queen Elizabeth",
  "Barack Obama",
  "Elon Musk",
  "Vladimir Putin",
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Johan Cruijff",
  "Angela Merkel",
  "Beyoncé",
  "Keukenhof",
  "De Veluwe",
  "De Eifeltoren",
  "Colosseum",
  "Japan",
  "China",
  "Inca's",
  "Telefoon",
  "Laptop",
  "PC",
  "Computer",
  "Microsoft",
  "Google",
  "Bol.com",
  "Pen",
  "Gum",
  "Sneeuw",
  "Sneeuwpop",
  "Berg",
  "Heuvel",
  "Ruimteschip",
  "Mens",
  "Tijd",
  "Rekenmachine",
  "Oplader",
  "Camera",
  "Zaklamp",
  "Boom",
  "Bos",
  "Bosje",
  "Appel",
  "Peer",
  "Banaan",
  "Tomaat",
  "Spruitjes",
  "Witlof",
  "Papier",
  "Draden",
  "Lego",
  "Nerf pistool",
  "Kartonnen oos",
  "Speaker",
  "Play mobiel",
  "Boek",
  "Eerste kamer",
  "Tweede kamer",
  "Mark Rutte",
  "PVV",
  "VVD",
  "GroenLinks",
  "Partij voor de dieren",
  "Schrijven",
  "Printer",
  "Koraal",
  "App",
  "Website",
  "Kunstmatige Inteligentie",
  "WiFi",
  "Notitie",
  "Frans Bouwer",
  "Enzoknol",
  "Mr. Beast",
  "Mr. Bean",
  "Cartoon",
  "Anime",
  "Rick Astley",
  "Phineas en Ferb",
  "Huiswerk",
  "Disney",
  "Marvel",
  "Pixar",
  "Minions",
  "Rommel",
  "Zakdoek",
  "Inkt",
  "USB",
  "Poster",
  "Selfie",
  "3D Printer",
  "Playstation 4",
  "XBox",
  "Wii",
  "Nintendo",
  "Mario",
  "Luigi",
  "Maria kart",
  "Postzegel",
  "QR code",
  "Drone",
  "Traktor",
  "Meta (net zoals Facebook)"
]

export function getFiveUniqueRandomSubjects() {
  const randomIndex = () => Math.floor(Math.random() * onderwerpen.length)

  /** @type {number[]} */
  const indexes = []
  for (let i = 0; i < 5; i++) {
    let proposedIndex = randomIndex()
    while (indexes.includes(proposedIndex)) {
      proposedIndex = randomIndex()
    }
    indexes.push(proposedIndex)
  }

  return indexes.map(index => onderwerpen[index])
}